license="All rights reserved"

modLoader="javafml"

loaderVersion="[45,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

[[mods]] #mandatory

modId="recruits"

version="1.10.6"

displayName="Recruits Mod"
updateJSONURL="https://raw.githubusercontent.com/talhanation/recruits/main/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/recruits"

logoFile="logo.png"

credits="talhanation"

authors="talhanation"
# The description text for the mod (multi line!) (#mandatory)
description='''
This Mod adds hire-able Villager Recruits with different Ranks like in M&B-Bannerlord into Minecraft.
'''
